### ISSUE TITLE
Branch management: The three roads

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/dev-kit#153]
Currently, we manage two branches: The stable one and the master one.

This works great, but this will make big problems when we will start releasing new majors.

Concrete case with admin-bundle and core-bundle:

If we release core-bundle right now, the logic would says that 3.x is not maintained anymore.

But, admin-bundle wont be compatible with core-bundle 4.0 right now. So user will still use the legacy branch of core-bundle waiting compatibility.

But what if a bug is found on core-bundle 3.x? Should we refuse the fix? I don't think so.

This is why I propose to maintains 3 branches starting the next major:
- `master`: The unstable branch, like actual (5.x for core-bundle)
- `stable`: For BC features and deprecation (4.x for core-bundle)
- `legacy`: For bug fixes. All bug-fixes should be submitted here except those concerning a feature added on the `stable` branch.

Any suggestions?

The dispatcher has to be updated before releasing new majors.

**Comment by greg0ire** [comment]
What about :

- `unstable`
- `stable`
- `stable-as-fuck` 

?

More seriously? What are these ? Some sort of branch alias ? Where will we use these names ?

**Comment by Soullivaneuh** [comment]
Those are just labels to represent branches. Names will still have the same format.

Example with core-bundle, when we will release the 4.0 tag, it will be:

* `5.x` (unstable)
* `4.x` (stable)
* `3.x` (legacy)

You can compare the legacy as the "Old stable" of PHPUnit: https://phpunit.de/

Sorry if this was not enough accurate.

**Comment by greg0ire** [comment]
> Sorry if this was not enough accurate.

No problem, just wondering if we are going to use them in the documentation or also in code / CI configuration, but time will tell I guess ;)

Anyhow I'm completely on board with this :+1:

**Comment by OskarStark** [comment]
> Anyhow I'm completely on board with this 👍

me too!

**Comment by javiereguiluz** [comment]
Just asking ... why don't you use the exact same branching policy of Symfony? Thanks!

**Comment by Soullivaneuh** [comment]
> Just asking ... why don't you use the exact same branching policy of Symfony? Thanks!

You mean minor branches like 2.3, 2.7, 2.8?

Simple: We don't have enough time and resources for that.

See the old 2.4.x-dev branch. Unstable, not tag from months and everybody was using it.

**Comment by ju1ius** [comment]
Or use a [monorepo](https://www.youtube.com/watch?v=4w3-f6Xhvu8), synchronize versions between all packages, and never worry about that again ? :trollface:

**Comment by Soullivaneuh** [comment]
@ju1ius Outside the troll, I think the monorepo is interesting for a package than can be installed and used full stack, like Symfony.

If we create a sonata monorepo package, it will include lot of not necessary repositories.

Why should I care to have PropelAdmin if I use doctrine for example?

Plus, some repositories have more restrictions than other. This is the case for user-bundle or page-bundle, not compatible yet with Symfony 3 because of sub-dependencies...

Maybe a monorepo for *some* of the packages? We may discuss about it later, but let's concentrate on the issue subject right now. :wink:

**Comment by ju1ius** [comment]
>  let's concentrate on the issue subject right now.

Your debian-like branching model (unstable/stable/oldstable) makes a lot of sense, no doubt about that. :+1:

But reading this, there's something I don't quite get, and I'd like be clarified, if you don't mind.

You're talking about releasing core-bundle in a new version that is not compatible with admin-bundle.
Which, to me, means that their master branch are currently incompatible. Which means that developping on both bundles in their master branch is not possible. Which sounds pretty weird to my ears.

For me, in the model you describe, a package in it's `stable` branch should only depend on `stable` packages. Following this simple logic, a package in it's `unstable` branch should only depend on `unstable` packages. So at any time, a checkout (or composer install) of all repos in their `unstable` branch should result in a compatible (and installable) set of bundles. So on for `stable` and `oldstable`.
Am I right ?

I'm asking this, because it is not currently the case. For example `doctrine-orm-admin-bundle@dev-master` requires `admin-bundle@^3.1`. So at the time I'm writing you just cannot composer-install both in their `unstable` version (idem for classification, page, news, media, et al.). Which confuses me because now I'm unsure which branch to use if I want to work on a cross-bundle PR.

:question:

**Comment by Soullivaneuh** [comment]
> You're talking about releasing core-bundle in a new version that is not compatible with admin-bundle.
Which, to me, means that their master branch are currently incompatible. Which means that developping on both bundles in their master branch is not possible. Which sounds pretty weird to my ears.

Wrong. Admin bundle depends on core-bundle, but not the reverse. Code bundle is a package that can be used alone.

> For me, in the model you describe, a package in it's stable branch should only depend on stable packages. Following this simple logic, a package in it's unstable branch should only depend on unstable packages.

Wrong too, sorry. :stuck_out_tongue: 

This was right with the old branching management because they was trying to follow Symfony versions  (if you take a look, no 1.x version for admin-bundle).

That's was not the good way. Now we fully respect semver. If core-bundle does not need lot of regularly change but admin-bundle does, we could have later a core-bundle 5.0 but a admin-bundle 12.0. What is the problem? Admin-bundle 12 could require core-bundle `^5.0`. Or to make upgrade for smoother: `^4.0 || ^5.0`.

> I'm asking this, because it is not currently the case. For example doctrine-orm-admin-bundle@dev-master requires admin-bundle@^3.1. So at the time I'm writing you just cannot composer-install both in their unstable version (idem for classification, page, news, media, et al.).

Packages are separated. Master does not mean "compatible with master one of other". It does just mean "this is here you have breaking changes", that's all.

Two special cases:

* block-bundle and admin-bundle
* classification-bundle and media-bundle

Those have circular dependencies and *might* cause issues. This have to be solved BTW by removing the circular dependencies.

> Which confuses me because now I'm unsure which branch to use if I want to work on a cross-bundle PR.

Simple the last stable one. :smile:

**Comment by ju1ius** [comment]
Still have an itch...
Seems to me that you're basically saying that the `unstable`, `stable` and `legacy` are just shortcut names, that yield no meaning as regard to inter-package consistency.

But if so then how are users supposed to find their way through the documentation ?
Like:
> I browse the doc for admin-bundle, choose version 4.2, then go to doctrine-orm and have to choose between 5.9, 6.2 and 7.3, wait... wat?

Or is it just an exception for `unstable` branches, which would not be documented at all ?

**Comment by Soullivaneuh** [comment]
> that yield no meaning as regard to inter-package consistency.

Yeah and this is normal as packages are independents.

> But if so then how are users supposed to find their way through the documentation ?

Based on what? For a new project, I don't see why they should choose which version to use. Just run:

```bash
composer require sonata-project/admin-bundle sonata-project/doctrine-orm-admin-bundle
```

And you will get the last stable packages, compatible each other.

> Or is it just an exception for `unstable` branches, which would not be documented at all ?

Unstable branche **are** documented. Example: https://sonata-project.org/bundles/admin/master/doc/index.html

**Comment by ju1ius** [comment]
> But if so then how are users supposed to find their way through the documentation ?

You didn't understand the question. Currently when **browsing the documentation website** you can select the desired bundle documentation version you want to read (the dropdown menu on the top right).

If, quote, «the `unstable`, `stable` and `legacy` are just shortcut names, that yield no meaning as regard to inter-package consistency.», then for each bundle documentation page this menu will contain completely different version numbers, with no "breadcrumb" or "pointer" to follow when reading the docs in a linear fashion.
Given that composer.json only lists **explicitely** required packages, in order to know which documentation version you should read for a particular bundle, you'd have to constantly refer to your **composer.lock**. :scream: 

Do you get my point ?

**Comment by Soullivaneuh** [comment]
> Currently when browsing the documentation website you can select the desired bundle documentation version you want to read (the dropdown menu on the top right).

Yeah, and it's redirected by default to the current stable version.

> If, quote, «the unstable, stable and legacy are just shortcut names, that yield no meaning as regard to inter-package consistency.», then for each bundle documentation page this menu will contain completely different version numbers, with no "breadcrumb" or "pointer" to follow when reading the docs in a linear fashion.

Well, if this is just about that, I may improve this by adding those labels next to the version number, on the select.

>  in order to know which documentation version you should read for a particular bundle, you'd have to constantly refer to your composer.lock. :scream:

False problem. You have `composer show sonata-project/*` for that.

Plus, in this case, you have the "problem" for each installed package on your project, not only Sonata ones.

> Do you get my point ?

Yes, at least I hope! :smile:

**Comment by ju1ius** [comment]
> Well, if this is just about that, I may improve this by adding those labels next to the version number, on the select.

Okay so now I do not even know if I exist. :laughing: 
Can you just answer yes or no for the following:

If, for each bundle, regardless of the actual version numbers, you were to add the following branch aliases:
dev-stable => 'stable.branch.x-dev',
dev-legacy => 'legacy.branch.x-dev',
dev-master => 'unstable.branch.x-dev',

1. Should a composer install of all bundles `@dev-stable` succeed ?
2. Should a composer install of all bundles `@dev-legacy` succeed ?
3. Should a composer install of all bundles `@dev-master` succeed ?

**Comment by Soullivaneuh** [comment]
> If, for each bundle, regardless of the actual version numbers, you were to add the following branch ?> > aliases:
> dev-stable => 'stable.branch.x-dev',
> dev-legacy => 'legacy.branch.x-dev',
> dev-master => 'unstable.branch.x-dev',

Ok so I think this time you didn't understand the goal. :-)

I never say I would use those labels, this is just a **representation**.

See this comment: https://github.com/sonata-project/dev-kit/issues/153#issuecomment-225029815

Actual version number branch aliases will be kept **as is**. The **only** difference is we will maintain 3 branches instead of 2 starting the next major of each bundle.

**Comment by greg0ire** [comment]
@ju1ius : I think the problem is you're not viewing the dependencies as a tree. Before, when we had sort of synchronization with symfony, this made sense but now, a branch of leaf package should not allow a branch of a dependency, but only *tags*, which are by definition stable. It should allow both tags from the stable and legacy branches so that we can start by releasing a new major version of the core bundle, then make the admin bundle compatible with it on its unstable branch, then release a new major version of the admin bundle. So in short, with semver, we should not try to synchronise branches, we should treat sonata core like any other dependency instead.

**Comment by Soullivaneuh** [comment]
> we can start by releasing a new major version of the core bundle, then make the admin bundle compatible with it on its unstable branch, then release a new major version of the admin bundle.

Nearly true. We can also make it compatible on the current stable branch of admin-bundle if possible. E.g.:  `^3.0 || ^4.0`.

That would be the recommended and smoother way IMHO.

**Comment by greg0ire** [comment]
> on the current stable branch of admin-bundle if possible

i.e. if there is no BC-break, and yes, that's even better if it is doable.

**Comment by ju1ius** [comment]
> a branch of leaf package should not allow a branch of a dependency, but only tags, which are by definition stable. It should allow both tags from the stable and legacy branches so that we can start by releasing a new major version of the core bundle, then make the admin bundle compatible with it on its unstable branch, then release a new major version of the admin bundle.

Thanks @greg0ire, the way you put it makes it very clear :bulb:

**Comment by Soullivaneuh** [comment]
> Thanks @greg0ire, the way you put it makes it very clear :bulb:  :tada:

Well, next time I post this kind of issue I will ask @greg0ire for translation. :trollface: :wink:

**Comment by Soullivaneuh** [comment]
Google Authenticator 2.0 has been released: https://github.com/sonata-project/GoogleAuthenticator/releases/tag/2.0.0

This is the beta test for the next majors.

I'm updating dev-kit right now.
