### ISSUE TITLE
What about GoogleAuthenticator?

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#184]
Do we still support this repository, because issues have been disabled.

It looks like we use some stuff from the dev-kit, but the `README.md` file looks different.

If we still support it, we should do some things:
- [ ] Add vendor prefix to the namespace
- [ ] Rename `lib` directory to `src`
- [ ] <strike>Rename `tests` to `test`</strike>
- [x] Update the autoloader for production (remove tests)
- [ ] add some docs
- [ ] Move sample to the docs 
- [ ] Remove `forked from ...`, because the origin is dead and not maintained anymore

**Comment by Soullivaneuh** [comment]
> Do we still support this repository, because issues have been disabled.

Maybe a mistake. cc @rande for confirmation.

> It looks like we use some stuff from the dev-kit, but the README.md file looks different.

Normal. The documentation is not online so I can't normalize it. Same for exporter and cache.

See: https://github.com/sonata-project/dev-kit/blob/42389c1da8416035ca6422636da0e8a89bad42ed/config/projects.yml#L234-L237

> Rename tests to Test

:-1: as I explained in https://github.com/sonata-project/cache/pull/45#issuecomment-228594969

But we can rename it to `test` instead of `test` because all the other bundle following this structure under sonata are not using plural (see exporter and cache).

**Comment by core23** [comment]
> But we can rename it to `test` instead of `test` because all the other bundle following this structure under sonata are not using plural (see exporter and cache).

👍 for `test` directory instead of `tests`

**Comment by core23** [comment]
@rande Can you say something to the `GoogleAuthenticator` library?

**Comment by core23** [comment]
Show we allow issues again?

**Comment by greg0ire** [comment]
Why were they disabled?

**Comment by core23** [comment]
No idea, maybe because it's a fork?

**Comment by greg0ire** [comment]
Might be the reason indeed!

**Comment by jordisala1991** [comment]
Everything seems to be already fixed.

Closing. If you find something that is not, please open an issue on the googleAuthenticator repository, because it will be easier to track, dev-kit for general issues only.
