### ISSUE TITLE
Should we drop FOSUserBundle

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#189]
Looks like the project is dead, because there is no further reaction to this [comment](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2067#issuecomment-217445228). Also the [milestone list](https://github.com/FriendsOfSymfony/FOSUserBundle/milestone/4) has no visible changes. Same for the released versions. The last one is from September!

Should we drop the FOS bundle and move this stuff to our UserBundle, because we modify most stuff to our needs. 

IMHO this can be done without any problems, because only the SonataUserBundle uses classes from the FOS bundle.

**Comment by Soullivaneuh** [comment]
I disagree.

It will be a lot harder IMHO because we will have to manage the whole FOSUser features and logic our-self.

Plus, the project is not really "dead". Several commits are added and PR merged.

So yes, they don't have so such time to merge the rest and push a stable version, but the 2.0 is really good and working (already tested).

Maybe we should ask the project contributor to propose some help?

Or at least, if they don't want to use it, in this case propose a migration onto our namespace.

But a fork is not an option for now IMHO.

**Comment by sstok** [comment]
If you want to fork the FOSUserBundle you may also be interested in the https://github.com/rollerworks/RollerworksMultiUserBundle which adds support for multiple user systems, it's a hack and is no longer maintained but with Sonata it may receive some much needed TLC 😄

**Comment by core23** [comment]
We got some good news 👍 

> I will work on releasing FOSUserBundle 2.x in the next few days. 

https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2167#issuecomment-232025427

**Comment by tuxayo** [comment]
There is still a concern about the viability of FOSUserBundle because the maintainer difficulties are still there.
