### ISSUE TITLE
Add support for file deletions

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/dev-kit#261]
At the moment, files deleted in the dev-kit project template are not deleted when deploying.

Possible solutions:
- whitelist directories entirely managed through dev-kit
- list files to delete in a configuration file

cc @dbu @jlamur @electricMaxxx

**Comment by ElectricMaxxx** [comment]
Just for me: can you draw the steps what `dev-kit` does and does not? I can't even imagine what you mean with `deploy` in a ecosphere of git repositories.

**Comment by greg0ire** [comment]
@Soullivaneuh correct me if I'm wrong it uses github API to create PRs if it sees the project has files that differs from the project template it generates. It also merges said PRs, and merges lower branches into more recent branches if there are no conflicts.

**Comment by dbu** [comment]
i think a list of files that have been deleted in devkit and deletion should be propagated would make sense. the list of entirely devkit managed folders sounds ok too, except its rather invisible in the other repos what things are managed by devkit. we could add a .devkit file into those folders maybe, to mark them.

**Comment by jlamur** [comment]
https://github.com/sonata-project/dev-kit/blob/master/src/Console/Command/DispatchCommand.php#L257

This is the function that creates the diff. The problem is perhaps on [line 326](https://github.com/sonata-project/dev-kit/blob/master/src/Console/Command/DispatchCommand.php#L326) because of the `all => true` option.

From `man git-add`:

> Update the index not only where the working tree has a file matching <pathspec> but also where the index already has an entry. This adds, modifies, and removes index
           entries to match the working tree.
If no <pathspec> is given when -A option is used, all files in the entire working tree are updated **(old versions of Git used to limit the update to the current
           directory and its subdirectories)**.

I don't have enough time to get deeper into this at the moment.

**Comment by greg0ire** [comment]
@jlamur I don't think this is a `git add` issue: there is nothing to add because the deletion is simply not noticed and applied.

**Comment by jlamur** [comment]
@greg0ire you're right.

**Comment by Soullivaneuh** [comment]
> correct me if I'm wrong it uses github API to create PRs if it sees the project has files that differs from the project template it generates.

It use the API for all stuff except branch and PR creation. The API is not enough for a multi-files PR creation.

**Comment by VincentLanglet** [comment]
Adding a `DELETE_` prefix now delete the files.
