### ISSUE TITLE
[RFC] Move from Makefile to composer scripts

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#263]
Just stumbled upon the [composer scripts](https://getcomposer.org/doc/articles/scripts.md) section by reading some symfony flex articles. AFAIK with symfony flex some tasks will be moved to composer. Also there are some known players (zend, composer itself or guzzle) who are using composer instead of make.

Today we are using `Makefile`s and make for executing dev tasks for linting, testing and building docs. But we could also use the `scripts` section inside composer. Are there any differences between these files? Or are these methods interchangeable?

**Comment by greg0ire** [comment]
I think composer scripts are meant to be hooked up to Composer events, but you are not forced to, it just seems to be their initial purpose. I personally stick with Make on my projects : it provides more features like target dependencies, variables, and is adopted by flex to provide some make targets like `serve`. Finally, I think it is better to have tools that do one thing well rather than several things.

**Comment by Soullivaneuh** [comment]
I'm not against composer scripts, but like @greg0ire says, this is not enough advanced IMHO.

What about multi-lines tasks like the `lint` one?

What about `cd` command for `docs`?
