### ISSUE TITLE
[RFC] Move all docs to docs folder

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#328]
After applying the new folder structure to the repos, there are still some docs in the root directory, which could also be moved to the docs folder:

- `UPGRADE-3.0.md`
- `UPGRADE-*.md`
- `CHANGELOG.md`
- `CONTRIBUTING.MD`
- `README.MD`

Could / Should we do this?

**Comment by jlamur** [comment]
This is a matter of conventions here, it's very common to have these files at the root of projects.

Plus, github displays the content of `README.md` on the homepage of the project and propose to open the `CONTRIBUTING.md` file before submitting an issue / PR.

**Comment by greg0ire** [comment]
Gitlab goes even further IIRC. But maybe we could group the UPGRADE files in a dedicated directory.

**Comment by Soullivaneuh** [comment]
Theses files are too specifics to be moved.

Plus, if you have to check the upgrade file quickly to fix something wrong while upgrading, it should be on top for quick access.

Let's keep this as is.

Note: In order to not have to much files, we may discuss on another issue about removing old UPGRADE file on new major releases.
