### ISSUE TITLE
Handling repositories topics and decide what topics to use.

### ISSUE THREAD

**Issue by jlamur** [sonata-project/dev-kit#392]
We must decide what topics to use for the repositories (eg. [symfony](https://github.com/topics/symfony), [symfony-bundle](https://github.com/topics/symfony-bundle)).

There is an API available to edit topics (here https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository), but it states that:
> **Warning:** The API may change without advance notice during the preview period.

**Comment by jordisala1991** [comment]
The base for me would be: `symfony`, `symfony-bundle`, `php`, `bundle`, `sonata`

Then on each repository we could have some specific. Example:

admin-bundle: `admin`, `admin-generator`
media-bundle: `media-management`
user-bundle: `user-management`

IMO we could add them manually, and implement something on dev-kit at the same time (because that could take some time).

**Comment by OskarStark** [comment]
Please have a look here @VincentLanglet

**Comment by VincentLanglet** [comment]
Using `symfony`, `bundle` AND `symfony-bundle` seems redundant to me.

Anyway, I think we can close this in favor of https://github.com/sonata-project/dev-kit/issues/1026 now
