### ISSUE TITLE
[RFC] Drop older versions of Symfony on master

### ISSUE THREAD

**Issue by kunicmarko20** [sonata-project/dev-kit#394]
Yesterday, @jordisala1991 and I discussed on a [PR](https://github.com/sonata-project/SonataCacheBundle/pull/205#pullrequestreview-97387446) about this, as CacheBundle is soon ready for a release maybe it is time to think about dropping anything lower than Symfony 3.4 on master branches. Currently, Symfony is giving [support for bug fixes](https://symfony.com/roadmap) for sf 3.4 and up. This has already been done for [DashboardBundle](https://github.com/sonata-project/dev-kit/pull/389). WDYT @sonata-project/contributors ?

**Comment by jordisala1991** [comment]
Stable branches: 2.8, 3.4 (we are currently on 3.2, but soon should be 3.3) and 4.0
Unstable branches: 3.4, 4.0

**Comment by kunicmarko20** [comment]
3.3 is getting only security fixes, maybe stable should also be 3.4?

**Comment by jordisala1991** [comment]
To be honest, I would say yes, but for 3.0 and 3.1 we dropped them when they ended the security fixes period

**Comment by kunicmarko20** [comment]
ping @sonata-project/contributors

**Comment by greg0ire** [comment]
Ok for dropping <3.4 on master

**Comment by kunicmarko20** [comment]
Summoning rest of @sonata-project/contributors, we need your opinion. This is blocking https://github.com/sonata-project/SonataCacheBundle/pull/205 and it is a big thing (so we all have to be on the same page).

**Comment by jordisala1991** [comment]
Ping @OskarStark @core23 @Soullivaneuh

**Comment by core23** [comment]
I'm okay with a <3.4 drop an the dev-branches

**Comment by Soullivaneuh** [comment]
It is not an issue about which version we should drop on each branch. The contributing guide is quite clear about that: At least one LTS must be supported.

Currently, the last LTS is 3.4. So there is no subject about removing 3.4 on master on not. Until a new LTS is out, we must keep the support on **both stable and master**.

Remember we can release a new major at any moment. If you already drop a LTS version on master, we will be stuck.

If you think the contributing guide is not enough clear about that, feel free for a PR on dev-kit. Otherwise, please close the issue.
