### ISSUE TITLE
Rename pedantic label

### ISSUE THREAD

**Issue by kunicmarko20** [sonata-project/dev-kit#411]
One of the contributors was disapointed and confused when I added `pedantic` label.

Check the issue: https://github.com/sonata-project/SonataAdminBundle/pull/5088

Contributor was disapointed because the definition for pedantic is:

>excessively concerned with minor details or rules; overscrupulous.

Should we consider renaming it?

**Comment by greg0ire** [comment]
If we find a  good alternative, maybe.

**Comment by OskarStark** [comment]
`no changelog needed` ??

**Comment by kunicmarko20** [comment]
`no release needed` sounds ok?

**Comment by greg0ire** [comment]
Other proposals (ordered by my own preference) :

- `release independent`
- `versionless`
- `meticulous`

**Comment by jordisala1991** [comment]
releaseless... joke, I like release independent too

**Comment by kunicmarko20** [comment]
I guess we have a new name then? 😄

**Comment by greg0ire** [comment]
@sstok proposes `maintenance`

**Comment by OskarStark** [comment]
everything is "maintenance", so I am against it 👎

**Comment by kunicmarko20** [comment]
`release independent`then?

**Comment by kunicmarko20** [comment]
ping @covex-nn @Soullivaneuh

**Comment by covex-nn** [comment]
I liked `pedantic` (it was funny), but `release independent` is fine too

**Comment by greg0ire** [comment]
I found it, and I like to be funny, but if it hurts some people, let's remove it, don't want to lose contributors over that :P

**Comment by Soullivaneuh** [comment]
It's hurt people? Is that a joke? Guys, it's just a label! :man_facepalming: 

If it's **very** important, let's rename it but let's keep it simple and clear, with one word.

`meticulous` for example, would be acceptable IMO.

**Comment by Soullivaneuh** [comment]
And if `pedantic` hurt people, the C compiler should be also contested. :trollface:

**Comment by greg0ire** [comment]
The C compiler is very old, and this is where I got that idea from. Not sure it's the best reference for this. Anyway, you can check the issue in the first message, and see that yes @phansys was apparently offended by this, and IIRC he wasn't the only one. @phansys, feel free to elaborate here about how this slight misinterpretation might have lead to a contribution boycott from you.

**Comment by phansys** [comment]
https://en.wikipedia.org/wiki/Pedant#Connotation:
>The term in English is typically used with a **negative connotation** to refer to someone who is over-concerned with minutiae and whose tone is condescending.

**Comment by greg0ire** [comment]
> with one word

I'd rather have something meaningful and with several words than something with one word but that fails to convey the meaning we want it to.

**Comment by Soullivaneuh** [comment]
> The C compiler is very old, and this is where I got that idea from. Not sure it's the best reference for this. 

Change nothing, in that case you should attack the creator of the C compiler too. :trollface: 

Outside the troll, guys it's just a label. It's seems quite obvious we don't want to insult anyone with a label. If this kind of word is used on a compiler (for example), maybe you should consider the usage of the Shakespeare language is not always relevant for technical stuff?

If you can't sleep because of it, I'm not against to change it. The issue is: dev-kit was not designed to just update label content for now. If you change the config, it will remove all the actual "pedantic" labels of current issues/PR and not replace them by the new one, this is not acceptable.
If all of you want the change I'll update dev-kit for that for sure, but when I will have time for this non-critical change, certainly starting the next week or week-end of June.

> I'd rather have something meaningful and with several words than something with one word but that fails to convey the meaning we want it to.

No need to make a `This is interesting but we don't need a change-log` "label" for that neither. Of course I exaggerate, but you know what I mean.

The first goal of the "Pedantic" label is about change that does not need a release (code typo, tests addition etc...). We may simply name it "No release", but as for "Maintenance", it's quite global and will be confusing with the "docs" label.

`meticulous` looks fine to me. Maybe `miscellaneous`? I don't know. In any case my first vote is just to keep `pedantic` and get things more complicated, but it seems I'll be the only one. :smile:

**Comment by greg0ire** [comment]
I thought it would be straightforward but if it is that much work, then maybe it is not worth it indeed.

**Comment by Soullivaneuh** [comment]
I can work on it if this issue provide so much pain to somebody. Let's be honest and create a vote on this comment.

:+1: To work on `pedantic` label rename.
:-1: If we should just stay as actual.

**Comment by greg0ire** [comment]
I abstain because I see pain on both sides.

**Comment by kunicmarko20** [comment]
`pedantic` will stay, closing.

**Comment by sstok** [comment]
Maintenance? 🤔 or style (while necessarily related to styling 😛 ).

Or dependless :trollface:
