### ISSUE TITLE
[RFC] Remove coupling to SonataAdminBundle

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#537]
This might be a controversial topic, but what do you think about removing the hard backend dependency to the **SonataAdminBundle** from our feature bundles and create new backend bundles (e.g. SonataNewsAdminBundle)? This would help to decouple our projects more and more.

The following projects are affected:
- SonataClassificationBundle
- SonataCommentBundle
- SonataMediaBundle
- SonataNewsBundle
- SonataUserBundle

## :+1: Pro
- We have lightweight bundles
- Easier extension
- Creating API driven bundles (interop with EasyAdmin, api-platform, ...)
- Faster release process
- Getting rid of _require-dev_ and _conflicting_ dependencies 

## :-1: Contra
- Doing a major release of a non-admin major release (e.g. Entity change) requires a major release of the admin release
- More projects
- More maintenance / release overhead
- Requires active communicate for the next major release ("Why is my feature now shown inside the admin dashboard?")

**Comment by VincentLanglet** [comment]
It would be interesting to know which % of sonata users are using those bundle without any interest in the AdminBundle.
My personal opinion is "none or not a lot".
This extra work, extra projects, extra maintenance, ... would be only useful for those users ; so I don't see a real interest.

This "remove coupling to SonataAdminBundle" was already started with the creation of the DatagridBundle.
- The Datagrid bundle will contains the classes needed by the backend like Datagrid, Pager, Filter, ProxyQuery
- When using a feature bundle like SonataMediaBundle without the SonataAdminBundle, only the DatagridBundle will be needed (for instance for the REST API)

This now have tons of issues:
- DatagridBundle and AdminBundle have some duplicated classes
- Worst, DatagridBundle and AdminBundle duplicated classes are slightly different/incompatible
- DatagridBundle is stick to a persistence bundle since it provide some ORM implementation of the interface
- Worst again, lot of improvements/fixes done in SonataDoctrineORMAdminBundle are not present in the DatagridBundle.

In a perfect world, we would have
- A DatagridBundle
- A SonataAdminBundle who require DatagridBundle
- A DatagridORMBundle who require DatagridBundle
- A SonataORMAdminBundle who require DatagridORMBundle and SonataAdminBundle

Controversial opinion: this is too much work/maintenance for the maintainers we have with too low benefit for the users we have.

Here, if I understand correctly for the SonataMediaBundle (and the other), we would have
- SonataMediaBundle with entities
- SonataMediaRestBundle with Apis, requiring SonataMediaBundle and SonataDatagridBundle 
- SonataMediaAdminBundle with Admin, requiring SonataMediaBundle and SonataAdminBundle

It's a nice idea on the paper. But I wonder if this would be really useful for the community we have. It could be interesting to create a poll on twitter with the sonata-project account in order to know which % of users are not using the AdminBundle.

Also if we plan to keep splitting bundle, a mono-repository would be better.

**Comment by core23** [comment]
> Controversial opinion: this is too much work/maintenance for the maintainers we have with too low benefit for the users we have.

As we have a lack of active core members at the moment, we should not spend any more time on this issue.

**Off topic:** I wonder if sonata is still a fancy project that is used for new projects / developers or if EasyAdmin is more famous. Symfony stopped listing us on their [project list](https://symfony.com/bundles) and it feels like *we* are the only people that open new pull requests and fix issues.

**Comment by VincentLanglet** [comment]
> **Off topic:** I wonder if sonata is still a fancy project that is used for new projects / developers or if EasyAdmin is more famous. Symfony stopped listing us on their [project list](https://symfony.com/bundles) and it feels like _we_ core developers are the only people that open new pull requests and fix issues.

The list from Symfony is pretty reduced, I assume they removed sonata because they want to promote EasyAdmin.
I merged multiple bug fix coming from non-core-developer and if we look at the stats it seems used a lot.
https://packagist.org/packages/sonata-project/admin-bundle/stats

The fact we didn't support Symfony 5 for a long time hurt sonata.
New projects/developers had to use Symfony 4 in order to use SonataAdmin (that's why we got issue about sf5/twig3).

But the stable release of the v4 should come soon.
