### ISSUE TITLE
Discussion: Making things final

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#79]
I would like to have a short discussion for `making everything final until someone asks`.

👍 I know that it is a good idea from the sonata developer point. We have more control over the source and can change more internal structures without ending in a BC break.

👎 But closing everything could frustrate other developers who might extend things we build. Not everybody is using GitHub when working on private projects or know who Git is working. Someone might be shy or might have bad english skills to ask for opening methods.

IMHO we should use the `final` keyword wisely to close funtions that might end in big trouble when overriding it.

**Comment by greg0ire** [comment]
> IMHO we should use the final keyword wisely to close funtions that might end in big trouble when overriding it. 

Just like private vs protected, I think we should do so if we can really think of at least one case where this is needed and it can't be solved by introducing a [well-defined extension point](http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html).

**Comment by Soullivaneuh** [comment]
:+1: By default but this have to be smartly done. I mean not make it `final` to make it `final`.

For example, if we ass `Box::getColor` to determine which color the box should be and return `blue` by default, obviously we will not make it `final` because it makes sense that this method can be overridden by `DangerBox` to return `red`.
