### ISSUE TITLE
Recommend using Doc block for test methods

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/dev-kit#92]
With PHPUnit you have two methods of telling that a method is actually a test:
- Start the name with test
- Put a annotation/doc block/phpdoc in the test

What method do you think is better?

In my opinion the restriction of having all test starting with the word test implies that you can't put a good names on what is actually the test doing. And also, it gets repetitive.

**Comment by Soullivaneuh** [comment]
> Start the name with test

Because it's much easier to quickly identify test method on code review.

**Comment by jordisala1991** [comment]
Let's see some examples:

https://gist.github.com/jordisala1991/4780e41aa6ee3dafd52640c708e4311f

In which one can you distinguish easily the test methods from the non-test methods?

(Note that there are three methods at the end just for configure reusable mocks, real example from sonataAdmin)

**Comment by Soullivaneuh** [comment]
For me, your code look harder to read because you are using `itSomething` and `dontSomethingElse`.

This is harder to search too. For example, if you want to quickly go to test functions you can quickly do a `Ctrl+F` and type `function test`.

You can't do this with easily your method.

Note: I'm surprised that @greg0ire didn't reacted about his love about the annotation usage. He is certainly sick. :stuck_out_tongue: :trollface:

**Comment by jordisala1991** [comment]
`Ctrl+F` `@test` :trollface: 

Maybe my test names are not good enough, but the point is trying to name a test with a name that expresses what is actually the test doing. testConfigureFormFields doesn't tell me a lot of what the test is testing apart from the function name...

About the annotation use. In this case is like the same. If you forget to put test on the name or do a misspell tets. The test will not run, just like if you forge the annotation or make it wrong.

I don't like annotations either. They are only useful when you are using a IDE. But in this case IMO is a bit better than the alternative.

**Comment by Soullivaneuh** [comment]
> `Ctrl+F` `@test` :trollface: 

Well. Indeed. :trollface: 

But I still having `test*` method name is better for consistency.

BTW, there are many tests already set up on sonata projects, all having the `test*` method.

It would be painful to update them just for a "design" opinion. As you said, both do the same.

**Comment by greg0ire** [comment]
@soullivaneuh : again, I'm away all WE ;) I have no strong feeling on this :
- annotations are bad only when they contain code IMO
- using them would allow us to name methods *à la* phpspec, see http://www.phpspec.net/en/latest/manual/getting-started.html , focusing on behavior instead of the name of the method
- but I would argue you can still name them test_it_converts_markdown_to_html
